version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Josemaria123
      POSTGRES_DB: asistente
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:Josemaria123@db:5432/asistente"
    volumes:
      - ./backend:/app
    command: sh -c "npx prisma migrate deploy && npm run dev"

  # frontend:
  #   build: ./frontend
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   environment:
  #     NEXT_PUBLIC_API_URL: "http://backend:8080/api"
  #   volumes:
  #     - ./frontend:/app

volumes:
  db-data:
