# Etapa de build
FROM node:20-alpine AS builder
WORKDIR /app

# Copiar deps y instalar
COPY package*.json ./
RUN npm ci

# Copiar el resto
COPY . .

# Generar cliente Prisma
RUN npx prisma generate

# Compilar TypeScript
RUN npm run build

# Etapa final
FROM node:20-alpine
WORKDIR /app

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma

ENV NODE_ENV=production
EXPOSE 8080
CMD ["npm", "run", "start"]
